// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: contrib/envoy/extensions/filters/http/debugging/v3/debugging.proto

package debuggingv3

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on HttpDebugging with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *HttpDebugging) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HttpDebugging with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in HttpDebuggingMultiError, or
// nil if none found.
func (m *HttpDebugging) ValidateAll() error {
	return m.validate(true)
}

func (m *HttpDebugging) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetStatPrefix()) < 1 {
		err := HttpDebuggingValidationError{
			field:  "StatPrefix",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for DebuggingRequestHeaderFlag

	if len(errors) > 0 {
		return HttpDebuggingMultiError(errors)
	}

	return nil
}

// HttpDebuggingMultiError is an error wrapping multiple validation errors
// returned by HttpDebugging.ValidateAll() if the designated constraints
// aren't met.
type HttpDebuggingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HttpDebuggingMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HttpDebuggingMultiError) AllErrors() []error { return m }

// HttpDebuggingValidationError is the validation error returned by
// HttpDebugging.Validate if the designated constraints aren't met.
type HttpDebuggingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpDebuggingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HttpDebuggingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HttpDebuggingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HttpDebuggingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HttpDebuggingValidationError) ErrorName() string { return "HttpDebuggingValidationError" }

// Error satisfies the builtin error interface
func (e HttpDebuggingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpDebugging.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpDebuggingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpDebuggingValidationError{}
