// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v5.29.3
// source: contrib/envoy/extensions/http/mcp_sse_stateful_session/envelope/v3alpha/envelope.proto

package v3alpha

import (
	_ "github.com/cncf/xds/go/udpa/annotations"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The extension implements MCP 241105 spec for SSE-based session tracking.
// It enables Envoy to handle session context in SSE event streams, allowing session ID
// and upstream host to be encoded/decoded as required by the protocol.
//
// When processing the response from the upstream, Envoy will check if the SSE data stream contains
// the session context. If the SSE data stream contains the session context, Envoy will join it and
// the upstream host as new session context using a separator.
//
// When processing the request from the downstream, Envoy will check if the url query params contain
// the session context. If the request contains the session context, Envoy will strip the
// upstream host from the session context.
// [#extension: envoy.http.mcp_sse_stateful_session.envelope]
type EnvelopeSessionState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The query parameter name used to track the session state in SSE data streams.
	// If the query parameter specified by this field is present in the SSE data stream,
	// the upstream host address will be encoded in following format:
	//
	// .. code-block:: none
	//
	//	sessionId={original_value}.{encoded_host}
	//
	// Where {encoded_host} is the Base64Url encoded host address.
	//
	// When processing the request from downstream, this extension will:
	// 1. Split the value at the last dot
	// 2. Decode the host address for upstream routing
	// 3. Keep only the original session ID in the request
	//
	// For example:
	//
	// .. code-block:: none
	//
	//	GET /path?sessionId=original_session_id.{encoded_host}
	//	# after processing:
	//	GET /path?sessionId=original_session_id
	//
	// Note: Uses Base64Url encoding for the host address and '.' as separator.
	ParamName string `protobuf:"bytes,1,opt,name=param_name,json=paramName,proto3" json:"param_name,omitempty"`
	// The list of patterns to match the chunk end in the SSE data stream.
	// Any of these patterns matched will be considered as the end of a chunk.
	// recommended value is ["\r\n\r\n", "\n\n", "\r\r"]
	// according to the HTML standard, the end of a server-sent-events' chunk can be
	// - \r\n\r\n (double Carriage-Return Line-Feed)
	// - \n\n (double Line-Feed)
	// - \r\r (double Carriage-Return)
	// https://html.spec.whatwg.org/multipage/server-sent-events.html#parsing-an-event-stream
	// Customized patterns can be added to match the chunk end pattern.
	ChunkEndPatterns []string `protobuf:"bytes,2,rep,name=chunk_end_patterns,json=chunkEndPatterns,proto3" json:"chunk_end_patterns,omitempty"`
	// The maximum size of the pending chunk.
	// If the pending chunk size is greater than this value, this filter will be disabled.
	// This is to prevent the filter from consuming too much memory when the SSE data stream is large.
	// In normal cases, the sessionId should be the initialize message and be in a small chunk.
	// The default value is 4KB.
	MaxPendingChunkSize int32 `protobuf:"varint,3,opt,name=max_pending_chunk_size,json=maxPendingChunkSize,proto3" json:"max_pending_chunk_size,omitempty"`
}

func (x *EnvelopeSessionState) Reset() {
	*x = EnvelopeSessionState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnvelopeSessionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeSessionState) ProtoMessage() {}

func (x *EnvelopeSessionState) ProtoReflect() protoreflect.Message {
	mi := &file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeSessionState.ProtoReflect.Descriptor instead.
func (*EnvelopeSessionState) Descriptor() ([]byte, []int) {
	return file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *EnvelopeSessionState) GetParamName() string {
	if x != nil {
		return x.ParamName
	}
	return ""
}

func (x *EnvelopeSessionState) GetChunkEndPatterns() []string {
	if x != nil {
		return x.ChunkEndPatterns
	}
	return nil
}

func (x *EnvelopeSessionState) GetMaxPendingChunkSize() int32 {
	if x != nil {
		return x.MaxPendingChunkSize
	}
	return 0
}

var File_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto protoreflect.FileDescriptor

var file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_rawDesc = []byte{
	0x0a, 0x56, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x2f, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2f,
	0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f,
	0x6d, 0x63, 0x70, 0x5f, 0x73, 0x73, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x66, 0x75, 0x6c,
	0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x65, 0x2f, 0x76, 0x33, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2f, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f,
	0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x3f, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2e,
	0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e,
	0x6d, 0x63, 0x70, 0x5f, 0x73, 0x73, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x66, 0x75, 0x6c,
	0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x65, 0x2e, 0x76, 0x33, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x1a, 0x1d, 0x75, 0x64, 0x70, 0x61, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xb1, 0x01, 0x0a, 0x14, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x0a, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x09, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x12, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x65, 0x6e, 0x64, 0x5f,
	0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x42, 0x0e,
	0xfa, 0x42, 0x0b, 0x92, 0x01, 0x08, 0x08, 0x01, 0x22, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x10,
	0x63, 0x68, 0x75, 0x6e, 0x6b, 0x45, 0x6e, 0x64, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x73,
	0x12, 0x33, 0x0a, 0x16, 0x6d, 0x61, 0x78, 0x5f, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f,
	0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x13, 0x6d, 0x61, 0x78, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x53, 0x69, 0x7a, 0x65, 0x42, 0xd8, 0x01, 0xba, 0x80, 0xc8, 0xd1, 0x06, 0x02, 0x10, 0x02,
	0x0a, 0x4d, 0x69, 0x6f, 0x2e, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e,
	0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x6d, 0x63, 0x70, 0x5f, 0x73, 0x73, 0x65, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x66, 0x75, 0x6c, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x65,
	0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x76, 0x33, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x42,
	0x0d, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x6e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6e, 0x76,
	0x6f, 0x79, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x67, 0x6f, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x2d, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62,
	0x2f, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x6d, 0x63, 0x70, 0x5f, 0x73, 0x73, 0x65, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x66, 0x75, 0x6c, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f,
	0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2f, 0x76, 0x33, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_rawDescOnce sync.Once
	file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_rawDescData = file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_rawDesc
)

func file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_rawDescGZIP() []byte {
	file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_rawDescOnce.Do(func() {
		file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_rawDescData)
	})
	return file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_rawDescData
}

var file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_goTypes = []interface{}{
	(*EnvelopeSessionState)(nil), // 0: envoy.extensions.http.mcp_sse_stateful_session.envelope.v3alpha.EnvelopeSessionState
}
var file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_init()
}
func file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_init() {
	if File_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnvelopeSessionState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_goTypes,
		DependencyIndexes: file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_depIdxs,
		MessageInfos:      file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_msgTypes,
	}.Build()
	File_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto = out.File
	file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_rawDesc = nil
	file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_goTypes = nil
	file_contrib_envoy_extensions_http_mcp_sse_stateful_session_envelope_v3alpha_envelope_proto_depIdxs = nil
}
