// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: contrib/envoy/extensions/http/mcp_sse_stateful_session/envelope/v3alpha/envelope.proto

package v3alpha

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on EnvelopeSessionState with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *EnvelopeSessionState) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EnvelopeSessionState with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EnvelopeSessionStateMultiError, or nil if none found.
func (m *EnvelopeSessionState) ValidateAll() error {
	return m.validate(true)
}

func (m *EnvelopeSessionState) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetParamName()) < 1 {
		err := EnvelopeSessionStateValidationError{
			field:  "ParamName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetChunkEndPatterns()) < 1 {
		err := EnvelopeSessionStateValidationError{
			field:  "ChunkEndPatterns",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetChunkEndPatterns() {
		_, _ = idx, item

		if utf8.RuneCountInString(item) < 1 {
			err := EnvelopeSessionStateValidationError{
				field:  fmt.Sprintf("ChunkEndPatterns[%v]", idx),
				reason: "value length must be at least 1 runes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	// no validation rules for MaxPendingChunkSize

	if len(errors) > 0 {
		return EnvelopeSessionStateMultiError(errors)
	}

	return nil
}

// EnvelopeSessionStateMultiError is an error wrapping multiple validation
// errors returned by EnvelopeSessionState.ValidateAll() if the designated
// constraints aren't met.
type EnvelopeSessionStateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EnvelopeSessionStateMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EnvelopeSessionStateMultiError) AllErrors() []error { return m }

// EnvelopeSessionStateValidationError is the validation error returned by
// EnvelopeSessionState.Validate if the designated constraints aren't met.
type EnvelopeSessionStateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EnvelopeSessionStateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EnvelopeSessionStateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EnvelopeSessionStateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EnvelopeSessionStateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EnvelopeSessionStateValidationError) ErrorName() string {
	return "EnvelopeSessionStateValidationError"
}

// Error satisfies the builtin error interface
func (e EnvelopeSessionStateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEnvelopeSessionState.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EnvelopeSessionStateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EnvelopeSessionStateValidationError{}
