//go:build vtprotobuf
// +build vtprotobuf

// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// source: contrib/envoy/extensions/http/mcp_sse_stateful_session/envelope/v3alpha/envelope.proto

package v3alpha

import (
	protohelpers "github.com/planetscale/vtprotobuf/protohelpers"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (m *EnvelopeSessionState) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EnvelopeSessionState) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *EnvelopeSessionState) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.MaxPendingChunkSize != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.MaxPendingChunkSize))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ChunkEndPatterns) > 0 {
		for iNdEx := len(m.ChunkEndPatterns) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ChunkEndPatterns[iNdEx])
			copy(dAtA[i:], m.ChunkEndPatterns[iNdEx])
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.ChunkEndPatterns[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ParamName) > 0 {
		i -= len(m.ParamName)
		copy(dAtA[i:], m.ParamName)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.ParamName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EnvelopeSessionState) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ParamName)
	if l > 0 {
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	if len(m.ChunkEndPatterns) > 0 {
		for _, s := range m.ChunkEndPatterns {
			l = len(s)
			n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
		}
	}
	if m.MaxPendingChunkSize != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.MaxPendingChunkSize))
	}
	n += len(m.unknownFields)
	return n
}
