// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: contrib/envoy/extensions/resource_monitors/cpu_usage/v3/cpu_usage.proto

package cpu_usagev3

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CpuUsageConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CpuUsageConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CpuUsageConfig with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CpuUsageConfigMultiError,
// or nil if none found.
func (m *CpuUsageConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *CpuUsageConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if val := m.GetSetpoint(); val <= 0 || val >= 1 {
		err := CpuUsageConfigValidationError{
			field:  "Setpoint",
			reason: "value must be inside range (0, 1)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for LowerBound

	// no validation rules for UpperBound

	if m.GetCoefficientP() <= 0 {
		err := CpuUsageConfigValidationError{
			field:  "CoefficientP",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetCoefficientI() <= 0 {
		err := CpuUsageConfigValidationError{
			field:  "CoefficientI",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetCoefficientD() <= 0 {
		err := CpuUsageConfigValidationError{
			field:  "CoefficientD",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetSmooth() <= 0 {
		err := CpuUsageConfigValidationError{
			field:  "Smooth",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CpuUsageConfigMultiError(errors)
	}

	return nil
}

// CpuUsageConfigMultiError is an error wrapping multiple validation errors
// returned by CpuUsageConfig.ValidateAll() if the designated constraints
// aren't met.
type CpuUsageConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CpuUsageConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CpuUsageConfigMultiError) AllErrors() []error { return m }

// CpuUsageConfigValidationError is the validation error returned by
// CpuUsageConfig.Validate if the designated constraints aren't met.
type CpuUsageConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CpuUsageConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CpuUsageConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CpuUsageConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CpuUsageConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CpuUsageConfigValidationError) ErrorName() string { return "CpuUsageConfigValidationError" }

// Error satisfies the builtin error interface
func (e CpuUsageConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCpuUsageConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CpuUsageConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CpuUsageConfigValidationError{}
