//go:build !disable_pgv
// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: contrib/envoy/extensions/filters/http/mcp_sse_stateful_session/v3alpha/mcp_sse_stateful_session.proto

package v3alpha

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on McpSseStatefulSession with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *McpSseStatefulSession) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on McpSseStatefulSession with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// McpSseStatefulSessionMultiError, or nil if none found.
func (m *McpSseStatefulSession) ValidateAll() error {
	return m.validate(true)
}

func (m *McpSseStatefulSession) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSessionState()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, McpSseStatefulSessionValidationError{
					field:  "SessionState",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, McpSseStatefulSessionValidationError{
					field:  "SessionState",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSessionState()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return McpSseStatefulSessionValidationError{
				field:  "SessionState",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Strict

	if len(errors) > 0 {
		return McpSseStatefulSessionMultiError(errors)
	}

	return nil
}

// McpSseStatefulSessionMultiError is an error wrapping multiple validation
// errors returned by McpSseStatefulSession.ValidateAll() if the designated
// constraints aren't met.
type McpSseStatefulSessionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m McpSseStatefulSessionMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m McpSseStatefulSessionMultiError) AllErrors() []error { return m }

// McpSseStatefulSessionValidationError is the validation error returned by
// McpSseStatefulSession.Validate if the designated constraints aren't met.
type McpSseStatefulSessionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e McpSseStatefulSessionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e McpSseStatefulSessionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e McpSseStatefulSessionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e McpSseStatefulSessionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e McpSseStatefulSessionValidationError) ErrorName() string {
	return "McpSseStatefulSessionValidationError"
}

// Error satisfies the builtin error interface
func (e McpSseStatefulSessionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMcpSseStatefulSession.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = McpSseStatefulSessionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = McpSseStatefulSessionValidationError{}

// Validate checks the field values on McpSseStatefulSessionPerRoute with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *McpSseStatefulSessionPerRoute) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on McpSseStatefulSessionPerRoute with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// McpSseStatefulSessionPerRouteMultiError, or nil if none found.
func (m *McpSseStatefulSessionPerRoute) ValidateAll() error {
	return m.validate(true)
}

func (m *McpSseStatefulSessionPerRoute) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	oneofOverridePresent := false
	switch v := m.Override.(type) {
	case *McpSseStatefulSessionPerRoute_Disabled:
		if v == nil {
			err := McpSseStatefulSessionPerRouteValidationError{
				field:  "Override",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofOverridePresent = true

		if m.GetDisabled() != true {
			err := McpSseStatefulSessionPerRouteValidationError{
				field:  "Disabled",
				reason: "value must equal true",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	case *McpSseStatefulSessionPerRoute_McpSseStatefulSession:
		if v == nil {
			err := McpSseStatefulSessionPerRouteValidationError{
				field:  "Override",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofOverridePresent = true

		if all {
			switch v := interface{}(m.GetMcpSseStatefulSession()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, McpSseStatefulSessionPerRouteValidationError{
						field:  "McpSseStatefulSession",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, McpSseStatefulSessionPerRouteValidationError{
						field:  "McpSseStatefulSession",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMcpSseStatefulSession()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return McpSseStatefulSessionPerRouteValidationError{
					field:  "McpSseStatefulSession",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}
	if !oneofOverridePresent {
		err := McpSseStatefulSessionPerRouteValidationError{
			field:  "Override",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return McpSseStatefulSessionPerRouteMultiError(errors)
	}

	return nil
}

// McpSseStatefulSessionPerRouteMultiError is an error wrapping multiple
// validation errors returned by McpSseStatefulSessionPerRoute.ValidateAll()
// if the designated constraints aren't met.
type McpSseStatefulSessionPerRouteMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m McpSseStatefulSessionPerRouteMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m McpSseStatefulSessionPerRouteMultiError) AllErrors() []error { return m }

// McpSseStatefulSessionPerRouteValidationError is the validation error
// returned by McpSseStatefulSessionPerRoute.Validate if the designated
// constraints aren't met.
type McpSseStatefulSessionPerRouteValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e McpSseStatefulSessionPerRouteValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e McpSseStatefulSessionPerRouteValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e McpSseStatefulSessionPerRouteValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e McpSseStatefulSessionPerRouteValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e McpSseStatefulSessionPerRouteValidationError) ErrorName() string {
	return "McpSseStatefulSessionPerRouteValidationError"
}

// Error satisfies the builtin error interface
func (e McpSseStatefulSessionPerRouteValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMcpSseStatefulSessionPerRoute.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = McpSseStatefulSessionPerRouteValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = McpSseStatefulSessionPerRouteValidationError{}
