// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: contrib/envoy/extensions/custom_cluster_plugins/cluster_fallback/v3/cluster_fallback.proto

package cluster_fallbackv3

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ClusterFallbackConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ClusterFallbackConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ClusterFallbackConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ClusterFallbackConfigMultiError, or nil if none found.
func (m *ClusterFallbackConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *ClusterFallbackConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.ConfigSpecifier.(type) {
	case *ClusterFallbackConfig_ClusterConfig_:
		if v == nil {
			err := ClusterFallbackConfigValidationError{
				field:  "ConfigSpecifier",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetClusterConfig()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ClusterFallbackConfigValidationError{
						field:  "ClusterConfig",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ClusterFallbackConfigValidationError{
						field:  "ClusterConfig",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetClusterConfig()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ClusterFallbackConfigValidationError{
					field:  "ClusterConfig",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ClusterFallbackConfig_WeightedClusterConfig_:
		if v == nil {
			err := ClusterFallbackConfigValidationError{
				field:  "ConfigSpecifier",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetWeightedClusterConfig()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ClusterFallbackConfigValidationError{
						field:  "WeightedClusterConfig",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ClusterFallbackConfigValidationError{
						field:  "WeightedClusterConfig",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetWeightedClusterConfig()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ClusterFallbackConfigValidationError{
					field:  "WeightedClusterConfig",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return ClusterFallbackConfigMultiError(errors)
	}

	return nil
}

// ClusterFallbackConfigMultiError is an error wrapping multiple validation
// errors returned by ClusterFallbackConfig.ValidateAll() if the designated
// constraints aren't met.
type ClusterFallbackConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClusterFallbackConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClusterFallbackConfigMultiError) AllErrors() []error { return m }

// ClusterFallbackConfigValidationError is the validation error returned by
// ClusterFallbackConfig.Validate if the designated constraints aren't met.
type ClusterFallbackConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClusterFallbackConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClusterFallbackConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClusterFallbackConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClusterFallbackConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClusterFallbackConfigValidationError) ErrorName() string {
	return "ClusterFallbackConfigValidationError"
}

// Error satisfies the builtin error interface
func (e ClusterFallbackConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClusterFallbackConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClusterFallbackConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClusterFallbackConfigValidationError{}

// Validate checks the field values on ClusterFallbackConfig_ClusterConfig with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ClusterFallbackConfig_ClusterConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ClusterFallbackConfig_ClusterConfig
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ClusterFallbackConfig_ClusterConfigMultiError, or nil if none found.
func (m *ClusterFallbackConfig_ClusterConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *ClusterFallbackConfig_ClusterConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RoutingCluster

	if len(errors) > 0 {
		return ClusterFallbackConfig_ClusterConfigMultiError(errors)
	}

	return nil
}

// ClusterFallbackConfig_ClusterConfigMultiError is an error wrapping multiple
// validation errors returned by
// ClusterFallbackConfig_ClusterConfig.ValidateAll() if the designated
// constraints aren't met.
type ClusterFallbackConfig_ClusterConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClusterFallbackConfig_ClusterConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClusterFallbackConfig_ClusterConfigMultiError) AllErrors() []error { return m }

// ClusterFallbackConfig_ClusterConfigValidationError is the validation error
// returned by ClusterFallbackConfig_ClusterConfig.Validate if the designated
// constraints aren't met.
type ClusterFallbackConfig_ClusterConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClusterFallbackConfig_ClusterConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClusterFallbackConfig_ClusterConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClusterFallbackConfig_ClusterConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClusterFallbackConfig_ClusterConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClusterFallbackConfig_ClusterConfigValidationError) ErrorName() string {
	return "ClusterFallbackConfig_ClusterConfigValidationError"
}

// Error satisfies the builtin error interface
func (e ClusterFallbackConfig_ClusterConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClusterFallbackConfig_ClusterConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClusterFallbackConfig_ClusterConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClusterFallbackConfig_ClusterConfigValidationError{}

// Validate checks the field values on
// ClusterFallbackConfig_WeightedClusterConfig with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ClusterFallbackConfig_WeightedClusterConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ClusterFallbackConfig_WeightedClusterConfig with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in
// ClusterFallbackConfig_WeightedClusterConfigMultiError, or nil if none found.
func (m *ClusterFallbackConfig_WeightedClusterConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *ClusterFallbackConfig_WeightedClusterConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetConfig() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ClusterFallbackConfig_WeightedClusterConfigValidationError{
						field:  fmt.Sprintf("Config[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ClusterFallbackConfig_WeightedClusterConfigValidationError{
						field:  fmt.Sprintf("Config[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ClusterFallbackConfig_WeightedClusterConfigValidationError{
					field:  fmt.Sprintf("Config[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ClusterFallbackConfig_WeightedClusterConfigMultiError(errors)
	}

	return nil
}

// ClusterFallbackConfig_WeightedClusterConfigMultiError is an error wrapping
// multiple validation errors returned by
// ClusterFallbackConfig_WeightedClusterConfig.ValidateAll() if the designated
// constraints aren't met.
type ClusterFallbackConfig_WeightedClusterConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClusterFallbackConfig_WeightedClusterConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClusterFallbackConfig_WeightedClusterConfigMultiError) AllErrors() []error { return m }

// ClusterFallbackConfig_WeightedClusterConfigValidationError is the validation
// error returned by ClusterFallbackConfig_WeightedClusterConfig.Validate if
// the designated constraints aren't met.
type ClusterFallbackConfig_WeightedClusterConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClusterFallbackConfig_WeightedClusterConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClusterFallbackConfig_WeightedClusterConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClusterFallbackConfig_WeightedClusterConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClusterFallbackConfig_WeightedClusterConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClusterFallbackConfig_WeightedClusterConfigValidationError) ErrorName() string {
	return "ClusterFallbackConfig_WeightedClusterConfigValidationError"
}

// Error satisfies the builtin error interface
func (e ClusterFallbackConfig_WeightedClusterConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClusterFallbackConfig_WeightedClusterConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClusterFallbackConfig_WeightedClusterConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClusterFallbackConfig_WeightedClusterConfigValidationError{}
