// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: contrib/envoy/extensions/filters/http/http_dubbo_transcoder/v3/http_dubbo_transcoder.proto

package http_dubbo_transcoderv3

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on HttpDubboTranscoder with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HttpDubboTranscoder) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HttpDubboTranscoder with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HttpDubboTranscoderMultiError, or nil if none found.
func (m *HttpDubboTranscoder) ValidateAll() error {
	return m.validate(true)
}

func (m *HttpDubboTranscoder) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRequestValidationOptions()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, HttpDubboTranscoderValidationError{
					field:  "RequestValidationOptions",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, HttpDubboTranscoderValidationError{
					field:  "RequestValidationOptions",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRequestValidationOptions()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return HttpDubboTranscoderValidationError{
				field:  "RequestValidationOptions",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if _, ok := HttpDubboTranscoder_UrlUnescapeSpec_name[int32(m.GetUrlUnescapeSpec())]; !ok {
		err := HttpDubboTranscoderValidationError{
			field:  "UrlUnescapeSpec",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetServicesMapping() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HttpDubboTranscoderValidationError{
						field:  fmt.Sprintf("ServicesMapping[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HttpDubboTranscoderValidationError{
						field:  fmt.Sprintf("ServicesMapping[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HttpDubboTranscoderValidationError{
					field:  fmt.Sprintf("ServicesMapping[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return HttpDubboTranscoderMultiError(errors)
	}

	return nil
}

// HttpDubboTranscoderMultiError is an error wrapping multiple validation
// errors returned by HttpDubboTranscoder.ValidateAll() if the designated
// constraints aren't met.
type HttpDubboTranscoderMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HttpDubboTranscoderMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HttpDubboTranscoderMultiError) AllErrors() []error { return m }

// HttpDubboTranscoderValidationError is the validation error returned by
// HttpDubboTranscoder.Validate if the designated constraints aren't met.
type HttpDubboTranscoderValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpDubboTranscoderValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HttpDubboTranscoderValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HttpDubboTranscoderValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HttpDubboTranscoderValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HttpDubboTranscoderValidationError) ErrorName() string {
	return "HttpDubboTranscoderValidationError"
}

// Error satisfies the builtin error interface
func (e HttpDubboTranscoderValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpDubboTranscoder.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpDubboTranscoderValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpDubboTranscoderValidationError{}

// Validate checks the field values on
// HttpDubboTranscoder_RequestValidateOptions with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *HttpDubboTranscoder_RequestValidateOptions) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// HttpDubboTranscoder_RequestValidateOptions with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in
// HttpDubboTranscoder_RequestValidateOptionsMultiError, or nil if none found.
func (m *HttpDubboTranscoder_RequestValidateOptions) ValidateAll() error {
	return m.validate(true)
}

func (m *HttpDubboTranscoder_RequestValidateOptions) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RejectUnknownQueryParameters

	// no validation rules for RejectUnknownMethod

	if len(errors) > 0 {
		return HttpDubboTranscoder_RequestValidateOptionsMultiError(errors)
	}

	return nil
}

// HttpDubboTranscoder_RequestValidateOptionsMultiError is an error wrapping
// multiple validation errors returned by
// HttpDubboTranscoder_RequestValidateOptions.ValidateAll() if the designated
// constraints aren't met.
type HttpDubboTranscoder_RequestValidateOptionsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HttpDubboTranscoder_RequestValidateOptionsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HttpDubboTranscoder_RequestValidateOptionsMultiError) AllErrors() []error { return m }

// HttpDubboTranscoder_RequestValidateOptionsValidationError is the validation
// error returned by HttpDubboTranscoder_RequestValidateOptions.Validate if
// the designated constraints aren't met.
type HttpDubboTranscoder_RequestValidateOptionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpDubboTranscoder_RequestValidateOptionsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HttpDubboTranscoder_RequestValidateOptionsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HttpDubboTranscoder_RequestValidateOptionsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HttpDubboTranscoder_RequestValidateOptionsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HttpDubboTranscoder_RequestValidateOptionsValidationError) ErrorName() string {
	return "HttpDubboTranscoder_RequestValidateOptionsValidationError"
}

// Error satisfies the builtin error interface
func (e HttpDubboTranscoder_RequestValidateOptionsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpDubboTranscoder_RequestValidateOptions.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpDubboTranscoder_RequestValidateOptionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpDubboTranscoder_RequestValidateOptionsValidationError{}

// Validate checks the field values on HttpDubboTranscoder_DubboMethodMapping
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *HttpDubboTranscoder_DubboMethodMapping) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// HttpDubboTranscoder_DubboMethodMapping with the rules defined in the proto
// definition for this message. If any rules are violated, the result is a
// list of violation errors wrapped in
// HttpDubboTranscoder_DubboMethodMappingMultiError, or nil if none found.
func (m *HttpDubboTranscoder_DubboMethodMapping) ValidateAll() error {
	return m.validate(true)
}

func (m *HttpDubboTranscoder_DubboMethodMapping) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := HttpDubboTranscoder_DubboMethodMappingValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetPathMatcher()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, HttpDubboTranscoder_DubboMethodMappingValidationError{
					field:  "PathMatcher",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, HttpDubboTranscoder_DubboMethodMappingValidationError{
					field:  "PathMatcher",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPathMatcher()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return HttpDubboTranscoder_DubboMethodMappingValidationError{
				field:  "PathMatcher",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetParameterMapping() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HttpDubboTranscoder_DubboMethodMappingValidationError{
						field:  fmt.Sprintf("ParameterMapping[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HttpDubboTranscoder_DubboMethodMappingValidationError{
						field:  fmt.Sprintf("ParameterMapping[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HttpDubboTranscoder_DubboMethodMappingValidationError{
					field:  fmt.Sprintf("ParameterMapping[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPassthroughSetting()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, HttpDubboTranscoder_DubboMethodMappingValidationError{
					field:  "PassthroughSetting",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, HttpDubboTranscoder_DubboMethodMappingValidationError{
					field:  "PassthroughSetting",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPassthroughSetting()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return HttpDubboTranscoder_DubboMethodMappingValidationError{
				field:  "PassthroughSetting",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return HttpDubboTranscoder_DubboMethodMappingMultiError(errors)
	}

	return nil
}

// HttpDubboTranscoder_DubboMethodMappingMultiError is an error wrapping
// multiple validation errors returned by
// HttpDubboTranscoder_DubboMethodMapping.ValidateAll() if the designated
// constraints aren't met.
type HttpDubboTranscoder_DubboMethodMappingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HttpDubboTranscoder_DubboMethodMappingMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HttpDubboTranscoder_DubboMethodMappingMultiError) AllErrors() []error { return m }

// HttpDubboTranscoder_DubboMethodMappingValidationError is the validation
// error returned by HttpDubboTranscoder_DubboMethodMapping.Validate if the
// designated constraints aren't met.
type HttpDubboTranscoder_DubboMethodMappingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpDubboTranscoder_DubboMethodMappingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HttpDubboTranscoder_DubboMethodMappingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HttpDubboTranscoder_DubboMethodMappingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HttpDubboTranscoder_DubboMethodMappingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HttpDubboTranscoder_DubboMethodMappingValidationError) ErrorName() string {
	return "HttpDubboTranscoder_DubboMethodMappingValidationError"
}

// Error satisfies the builtin error interface
func (e HttpDubboTranscoder_DubboMethodMappingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpDubboTranscoder_DubboMethodMapping.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpDubboTranscoder_DubboMethodMappingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpDubboTranscoder_DubboMethodMappingValidationError{}

// Validate checks the field values on HttpDubboTranscoder_DubboServiceMapping
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *HttpDubboTranscoder_DubboServiceMapping) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// HttpDubboTranscoder_DubboServiceMapping with the rules defined in the proto
// definition for this message. If any rules are violated, the result is a
// list of violation errors wrapped in
// HttpDubboTranscoder_DubboServiceMappingMultiError, or nil if none found.
func (m *HttpDubboTranscoder_DubboServiceMapping) ValidateAll() error {
	return m.validate(true)
}

func (m *HttpDubboTranscoder_DubboServiceMapping) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := HttpDubboTranscoder_DubboServiceMappingValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Version

	for idx, item := range m.GetMethodMapping() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HttpDubboTranscoder_DubboServiceMappingValidationError{
						field:  fmt.Sprintf("MethodMapping[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HttpDubboTranscoder_DubboServiceMappingValidationError{
						field:  fmt.Sprintf("MethodMapping[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HttpDubboTranscoder_DubboServiceMappingValidationError{
					field:  fmt.Sprintf("MethodMapping[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Group

	if len(errors) > 0 {
		return HttpDubboTranscoder_DubboServiceMappingMultiError(errors)
	}

	return nil
}

// HttpDubboTranscoder_DubboServiceMappingMultiError is an error wrapping
// multiple validation errors returned by
// HttpDubboTranscoder_DubboServiceMapping.ValidateAll() if the designated
// constraints aren't met.
type HttpDubboTranscoder_DubboServiceMappingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HttpDubboTranscoder_DubboServiceMappingMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HttpDubboTranscoder_DubboServiceMappingMultiError) AllErrors() []error { return m }

// HttpDubboTranscoder_DubboServiceMappingValidationError is the validation
// error returned by HttpDubboTranscoder_DubboServiceMapping.Validate if the
// designated constraints aren't met.
type HttpDubboTranscoder_DubboServiceMappingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpDubboTranscoder_DubboServiceMappingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HttpDubboTranscoder_DubboServiceMappingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HttpDubboTranscoder_DubboServiceMappingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HttpDubboTranscoder_DubboServiceMappingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HttpDubboTranscoder_DubboServiceMappingValidationError) ErrorName() string {
	return "HttpDubboTranscoder_DubboServiceMappingValidationError"
}

// Error satisfies the builtin error interface
func (e HttpDubboTranscoder_DubboServiceMappingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpDubboTranscoder_DubboServiceMapping.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpDubboTranscoder_DubboServiceMappingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpDubboTranscoder_DubboServiceMappingValidationError{}

// Validate checks the field values on
// HttpDubboTranscoder_DubboMethodMapping_ParameterMapping with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HttpDubboTranscoder_DubboMethodMapping_ParameterMapping) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// HttpDubboTranscoder_DubboMethodMapping_ParameterMapping with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HttpDubboTranscoder_DubboMethodMapping_ParameterMappingMultiError, or nil
// if none found.
func (m *HttpDubboTranscoder_DubboMethodMapping_ParameterMapping) ValidateAll() error {
	return m.validate(true)
}

func (m *HttpDubboTranscoder_DubboMethodMapping_ParameterMapping) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ExtractKeySpec

	// no validation rules for ExtractKey

	// no validation rules for MappingType

	if len(errors) > 0 {
		return HttpDubboTranscoder_DubboMethodMapping_ParameterMappingMultiError(errors)
	}

	return nil
}

// HttpDubboTranscoder_DubboMethodMapping_ParameterMappingMultiError is an
// error wrapping multiple validation errors returned by
// HttpDubboTranscoder_DubboMethodMapping_ParameterMapping.ValidateAll() if
// the designated constraints aren't met.
type HttpDubboTranscoder_DubboMethodMapping_ParameterMappingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HttpDubboTranscoder_DubboMethodMapping_ParameterMappingMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HttpDubboTranscoder_DubboMethodMapping_ParameterMappingMultiError) AllErrors() []error {
	return m
}

// HttpDubboTranscoder_DubboMethodMapping_ParameterMappingValidationError is
// the validation error returned by
// HttpDubboTranscoder_DubboMethodMapping_ParameterMapping.Validate if the
// designated constraints aren't met.
type HttpDubboTranscoder_DubboMethodMapping_ParameterMappingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpDubboTranscoder_DubboMethodMapping_ParameterMappingValidationError) Field() string {
	return e.field
}

// Reason function returns reason value.
func (e HttpDubboTranscoder_DubboMethodMapping_ParameterMappingValidationError) Reason() string {
	return e.reason
}

// Cause function returns cause value.
func (e HttpDubboTranscoder_DubboMethodMapping_ParameterMappingValidationError) Cause() error {
	return e.cause
}

// Key function returns key value.
func (e HttpDubboTranscoder_DubboMethodMapping_ParameterMappingValidationError) Key() bool {
	return e.key
}

// ErrorName returns error name.
func (e HttpDubboTranscoder_DubboMethodMapping_ParameterMappingValidationError) ErrorName() string {
	return "HttpDubboTranscoder_DubboMethodMapping_ParameterMappingValidationError"
}

// Error satisfies the builtin error interface
func (e HttpDubboTranscoder_DubboMethodMapping_ParameterMappingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpDubboTranscoder_DubboMethodMapping_ParameterMapping.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpDubboTranscoder_DubboMethodMapping_ParameterMappingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpDubboTranscoder_DubboMethodMapping_ParameterMappingValidationError{}

// Validate checks the field values on
// HttpDubboTranscoder_DubboMethodMapping_PathMatcher with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *HttpDubboTranscoder_DubboMethodMapping_PathMatcher) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// HttpDubboTranscoder_DubboMethodMapping_PathMatcher with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in
// HttpDubboTranscoder_DubboMethodMapping_PathMatcherMultiError, or nil if
// none found.
func (m *HttpDubboTranscoder_DubboMethodMapping_PathMatcher) ValidateAll() error {
	return m.validate(true)
}

func (m *HttpDubboTranscoder_DubboMethodMapping_PathMatcher) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MatchPattern

	// no validation rules for MatchHttpMethodSpec

	if len(errors) > 0 {
		return HttpDubboTranscoder_DubboMethodMapping_PathMatcherMultiError(errors)
	}

	return nil
}

// HttpDubboTranscoder_DubboMethodMapping_PathMatcherMultiError is an error
// wrapping multiple validation errors returned by
// HttpDubboTranscoder_DubboMethodMapping_PathMatcher.ValidateAll() if the
// designated constraints aren't met.
type HttpDubboTranscoder_DubboMethodMapping_PathMatcherMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HttpDubboTranscoder_DubboMethodMapping_PathMatcherMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HttpDubboTranscoder_DubboMethodMapping_PathMatcherMultiError) AllErrors() []error { return m }

// HttpDubboTranscoder_DubboMethodMapping_PathMatcherValidationError is the
// validation error returned by
// HttpDubboTranscoder_DubboMethodMapping_PathMatcher.Validate if the
// designated constraints aren't met.
type HttpDubboTranscoder_DubboMethodMapping_PathMatcherValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpDubboTranscoder_DubboMethodMapping_PathMatcherValidationError) Field() string {
	return e.field
}

// Reason function returns reason value.
func (e HttpDubboTranscoder_DubboMethodMapping_PathMatcherValidationError) Reason() string {
	return e.reason
}

// Cause function returns cause value.
func (e HttpDubboTranscoder_DubboMethodMapping_PathMatcherValidationError) Cause() error {
	return e.cause
}

// Key function returns key value.
func (e HttpDubboTranscoder_DubboMethodMapping_PathMatcherValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HttpDubboTranscoder_DubboMethodMapping_PathMatcherValidationError) ErrorName() string {
	return "HttpDubboTranscoder_DubboMethodMapping_PathMatcherValidationError"
}

// Error satisfies the builtin error interface
func (e HttpDubboTranscoder_DubboMethodMapping_PathMatcherValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpDubboTranscoder_DubboMethodMapping_PathMatcher.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpDubboTranscoder_DubboMethodMapping_PathMatcherValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpDubboTranscoder_DubboMethodMapping_PathMatcherValidationError{}

// Validate checks the field values on
// HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingMultiError, or nil
// if none found.
func (m *HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting) ValidateAll() error {
	return m.validate(true)
}

func (m *HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.HeadersSetting.(type) {
	case *HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughAllHeaders:
		if v == nil {
			err := HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingValidationError{
				field:  "HeadersSetting",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for PassthroughAllHeaders
	case *HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeaders_:
		if v == nil {
			err := HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingValidationError{
				field:  "HeadersSetting",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetPassthroughHeaders()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingValidationError{
						field:  "PassthroughHeaders",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingValidationError{
						field:  "PassthroughHeaders",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetPassthroughHeaders()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingValidationError{
					field:  "PassthroughHeaders",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingMultiError(errors)
	}

	return nil
}

// HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingMultiError is an
// error wrapping multiple validation errors returned by
// HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting.ValidateAll() if
// the designated constraints aren't met.
type HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingMultiError) AllErrors() []error {
	return m
}

// HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingValidationError is
// the validation error returned by
// HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting.Validate if the
// designated constraints aren't met.
type HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingValidationError) Field() string {
	return e.field
}

// Reason function returns reason value.
func (e HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingValidationError) Reason() string {
	return e.reason
}

// Cause function returns cause value.
func (e HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingValidationError) Cause() error {
	return e.cause
}

// Key function returns key value.
func (e HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingValidationError) Key() bool {
	return e.key
}

// ErrorName returns error name.
func (e HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingValidationError) ErrorName() string {
	return "HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingValidationError"
}

// Error satisfies the builtin error interface
func (e HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpDubboTranscoder_DubboMethodMapping_PassthroughSetting.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpDubboTranscoder_DubboMethodMapping_PassthroughSettingValidationError{}

// Validate checks the field values on
// HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeaders
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeaders) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeaders
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeadersMultiError,
// or nil if none found.
func (m *HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeaders) ValidateAll() error {
	return m.validate(true)
}

func (m *HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeaders) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeadersMultiError(errors)
	}

	return nil
}

// HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeadersMultiError
// is an error wrapping multiple validation errors returned by
// HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeaders.ValidateAll()
// if the designated constraints aren't met.
type HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeadersMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeadersMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeadersMultiError) AllErrors() []error {
	return m
}

// HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeadersValidationError
// is the validation error returned by
// HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeaders.Validate
// if the designated constraints aren't met.
type HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeadersValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeadersValidationError) Field() string {
	return e.field
}

// Reason function returns reason value.
func (e HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeadersValidationError) Reason() string {
	return e.reason
}

// Cause function returns cause value.
func (e HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeadersValidationError) Cause() error {
	return e.cause
}

// Key function returns key value.
func (e HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeadersValidationError) Key() bool {
	return e.key
}

// ErrorName returns error name.
func (e HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeadersValidationError) ErrorName() string {
	return "HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeadersValidationError"
}

// Error satisfies the builtin error interface
func (e HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeadersValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeaders.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeadersValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpDubboTranscoder_DubboMethodMapping_PassthroughSetting_PassthroughHeadersValidationError{}
